# MCP Server Services

read_config:
  name: Read Configuration File
  description: Read a Home Assistant configuration file
  fields:
    filename:
      name: Filename
      description: Name of the configuration file to read (e.g., configuration.yaml)
      required: true
      example: "configuration.yaml"
      selector:
        text:

write_config:
  name: Write Configuration File
  description: Write to a Home Assistant configuration file
  fields:
    filename:
      name: Filename
      description: Name of the configuration file to write
      required: true
      example: "automations.yaml"
      selector:
        text:
    content:
      name: Content
      description: Content to write to the file (YAML or JSON format)
      required: true
      selector:
        object:

list_configs:
  name: List Configuration Files
  description: List all configuration files in the Home Assistant config directory

get_config_value:
  name: Get Configuration Value
  description: Get a specific value from a configuration file
  fields:
    filename:
      name: Filename
      description: Name of the configuration file
      required: true
      example: "configuration.yaml"
      selector:
        text:
    key_path:
      name: Key Path
      description: Dot-separated path to the configuration key (e.g., homeassistant.name)
      required: true
      example: "homeassistant.name"
      selector:
        text:

set_config_value:
  name: Set Configuration Value
  description: Set a specific value in a configuration file
  fields:
    filename:
      name: Filename
      description: Name of the configuration file
      required: true
      example: "configuration.yaml"
      selector:
        text:
    key_path:
      name: Key Path
      description: Dot-separated path to the configuration key
      required: true
      example: "homeassistant.name"
      selector:
        text:
    value:
      name: Value
      description: Value to set
      required: true
      selector:
        text:

list_users:
  name: List Users
  description: List all users in Home Assistant

get_user:
  name: Get User
  description: Get details of a specific user
  fields:
    user_id:
      name: User ID
      description: The unique identifier of the user
      required: true
      example: "1234567890abcdef"
      selector:
        text:

list_integrations:
  name: List Integrations
  description: List all configured integrations (config entries)

get_integration:
  name: Get Integration
  description: Get details of a specific integration
  fields:
    entry_id:
      name: Entry ID
      description: The unique identifier of the config entry
      required: true
      example: "1234567890abcdef"
      selector:
        text:

list_devices:
  name: List Devices
  description: List all devices or devices from a specific domain
  fields:
    domain:
      name: Domain
      description: Optional domain filter (e.g., 'light', 'switch')
      required: false
      example: "light"
      selector:
        text:

get_device:
  name: Get Device
  description: Get details of a specific device
  fields:
    device_id:
      name: Device ID
      description: The unique identifier of the device
      required: true
      example: "1234567890abcdef"
      selector:
        text:

list_entities:
  name: List Entities
  description: List all entities or entities from a specific domain
  fields:
    domain:
      name: Domain
      description: Optional domain filter (e.g., 'light', 'switch')
      required: false
      example: "light"
      selector:
        text:

get_entity:
  name: Get Entity
  description: Get details and current state of a specific entity
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID
      required: true
      example: "light.living_room"
      selector:
        entity:

update_entity_state:
  name: Update Entity State
  description: Update the state of an entity
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to update
      required: true
      example: "light.living_room"
      selector:
        entity:
    state:
      name: State
      description: The new state value
      required: true
      example: "on"
      selector:
        text:
    attributes:
      name: Attributes
      description: Optional attributes to set
      required: false
      selector:
        object:

get_entity_history:
  name: Get Entity History
  description: Get historical state data for an entity
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID
      required: true
      example: "sensor.temperature"
      selector:
        entity:
    start_time:
      name: Start Time
      description: Optional start time (ISO format, defaults to 24 hours ago)
      required: false
      example: "2024-01-01T00:00:00+00:00"
      selector:
        text:
    end_time:
      name: End Time
      description: Optional end time (ISO format, defaults to now)
      required: false
      example: "2024-01-02T00:00:00+00:00"
      selector:
        text:
